### ISSUE TITLE
刚体-刚体耦合算法

### ISSUE THREAD

**Issue by HNUZhaoXiang** [chunleili/SPlisHSPlasH#3]
您好
我想请问一下，splishsplash中是怎么实现刚体-刚体耦合和刚体-边界耦合计算的，是通过PositionBasedDynamics库实现的吗

**Comment by chunleili** [comment]
> 您好 我想请问一下，splishsplash中是怎么实现刚体-刚体耦合和刚体-边界耦合计算的，是通过PositionBasedDynamics库实现的吗

刚体会在导入的时候被粒子化。然后用PBD库做刚体运动仿真。刚体与流体的耦合采用Boundary Condition处理。分为Akinci2012， Density Map, Volume map三种。总之在SPH中一切是粒子。

**Comment by HNUZhaoXiang** [comment]
是的，流固耦合用的是边界算法，刚体-刚体耦合好像是用的pbd库，看来是要取研究PBD库了
